WIP: Update documentation
defenseunicorns/doc-site-template pull request #9
Opened 2023-08-03 17:27 UTC by gscallon

Our pipelines team in Delivery is integrating the docs site template into our projects to improve the way we do documentation and standardize with the overall company's efforts. This PR contains any additional instructions, context, and information from our experience in utilizing the template.

The PR has been marked as a draft/WIP for now. The WIP tag will be removed once the PR is ready for review.

2023-08-10 21:19 UTC, bdfinst requested changes

2023-08-10 21:19 UTC, bdfinst commented on content/en/docs/codeSample.md
I suggested to Collin that we add documentation for this possible GitLab issue rather than show this as the recommended pattern since I've never seen this problem before, and we don't want to optimize for an edge case.

2023-08-11 12:15 UTC, eFAILution commented on content/en/docs/codeSample.md
Pushed changes that [add documentation in the form of comments](https://github.com/defenseunicorns/doc-site-template/pull/9/commits/6098cb2060d7512341defb4e381487714ce80df6) versus hardcoded fix. 
Also, [added documentation to hugo.toml](https://github.com/defenseunicorns/doc-site-template/pull/9/commits/19b1866beb24d7840f330141b9b2d808dea54b81) for building offline capable public dir.

2023-08-15 17:19 UTC, bdfinst commented on hugo.toml
> -[[module.mounts]]
Why is this mount being removed?

2023-08-15 18:01 UTC, eFAILution commented on hugo.toml
> -[[module.mounts]]
Didn't remove, but reorganized. Moved it to the top with other properties that need changed when deploying an offline public/.

2023-08-18 19:19 UTC, bdfinst approved these changes

2023-08-18 19:19 UTC, merged